from ll import LinkedList, Node


songs = [
    ('Losing It', 'Fisher', 'Losing It'),
    ('Red Light', 'Anyma', 'A Mirror Without Reflection'),
    ('Alive', 'Massano', 'Alive'),
    ('Realm of Consciousness', 'Chris Avantgarde', 'Realm of Consciousness'),
    ('Innerbloom', 'RUFUS DU SOL', 'Bloom'),
    ('Glue', 'Bicep', 'Bicep'),
    ('Lady (Hear Me Tonight)', 'Modjo', 'Modjo'),
    ('Music Sounds Better With You', 'Stardust', 'Music Sounds Better With You'),
    ('Latch', 'Disclosure', 'Settle'),
    ('Porcelain', 'Moby', 'Play'),
    ('D.A.N.C.E.', 'Justice', 'Cross'),
    ('One More Time', 'Daft Punk', 'Discovery'),
    ('Nightcall', 'Kavinsky', 'Outrun'),
    ('Voices', 'Russ Yallop', 'Voices'),
    ('Opus', 'Eric Prydz', 'Opus'),
    ('Strobe', 'Deadmau5', 'For Lack of a Better Name'),
    ('Endless', 'Tale Of Us', 'Endless'),
    ('Conjure', 'Maceo Plex', 'Conjure'),
    ('Starry Night', 'Peggy Gou', 'Starry Night'),
    ('Doppler', 'Charlotte de Witte', 'Doppler'),
    ('Exhale', 'Amelie Lens', 'Exhale'),
    ('Subzero', 'Ben Klock', 'Subzero'),
    ('Temptation', 'Solomun', 'Temptation'),
    ('Seeing Through Shadows', 'Dixon', 'Seeing Through Shadows'),
    ('Baby', 'Four Tet', 'Baby'),
    ('LesAlpx', 'Floating Points', 'Elaenia'),
    ('Immunity', 'Jon Hopkins', 'Immunity'),
    ('Space Is Only Noise If You Can See', 'Nicolas Jaar', 'Space Is Only Noise'),
    ('Cant Do Without You', 'Caribou', 'Our Love'),
    ('Loud Places', 'Jamie xx', 'In Colour'),
    ('Delilah (Pull Me Out of This)', 'Fred Again..', 'Actual Life'),
    ('Chances', 'Kaytranada', '99.9%'),
    ('Cherry', 'Mall Grab', 'Cherry'),
    ('Cola', 'CamelPhat', 'Cola'),
    ('Dont You', 'Lane 8', 'Little Bang'),
    ('Knee Deep', 'Hot Since 82', 'Knee Deep'),
    ('Bar A Thym', 'Kerri Chandler', 'Bar A Thym'),
    ('Your Love', 'Frankie Knuckles', 'Your Love'),
    ('Can You Feel It', 'Larry Heard', 'Can You Feel It'),
    ('Move Your Body', 'Marshall Jefferson', 'Move Your Body'),
    ('Keep On Jumpin', 'Todd Terry', 'Keep On Jumpin'),
    ('Lovelee Dae', 'Blaze', 'Lovelee Dae'),
    ('To Be in Love', 'Masters at Work', 'To Be in Love'),
    ('French Kiss', 'Lil Louis', 'French Kiss'),
    ('Pick Up', 'DJ Koze', 'Knock Knock'),
    ('Rej', 'Ame', 'Rej'),
    ('Gehts Noch', 'Roman Flugel', 'Gehts Noch'),
    ('Danube', 'Move D', 'Danube'),
    ('Fleece on Brain', 'Matthew Dear', 'Fleece on Brain'),
    ('Hubble', 'Actress', 'Hubble'),
    ('Around the World', 'Daft Punk', 'Homework'),
    ('Get Lucky', 'Daft Punk', 'Random Access Memories'),
    ('Harder Better Faster Stronger', 'Daft Punk', 'Discovery'),
    ('Da Funk', 'Daft Punk', 'Homework'),
    ('Digital Love', 'Daft Punk', 'Discovery'),
    ('Contact', 'Daft Punk', 'Random Access Memories'),
    ('Revolution 909', 'Daft Punk', 'Homework'),
    ('Technologic', 'Daft Punk', 'Human After All'),
    ('Robot Rock', 'Daft Punk', 'Human After All'),
    ('Instant Crush', 'Daft Punk', 'Random Access Memories'),
    ('Atlas', 'Bicep', 'Isles'),
    ('Gloves', 'Bicep', 'Bicep'),
    ('Rain', 'Bicep', 'Isles'),
    ('Saku', 'Bicep', 'Isles'),
    ('Vale', 'Bicep', 'Isles'),
    ('You and Me', 'Disclosure', 'Settle'),
    ('White Noise', 'Disclosure', 'Settle'),
    ('Running', 'Disclosure', 'Caracal'),
    ('Magnets', 'Disclosure', 'Caracal'),
    ('Omen', 'Disclosure', 'Caracal'),
    ('Sundream', 'RUFUS DU SOL', 'Bloom'),
    ('Say a Prayer for Me', 'RUFUS DU SOL', 'Surrender'),
    ('No Place', 'RUFUS DU SOL', 'Solace'),
    ('Treat You Better', 'RUFUS DU SOL', 'Solace'),
    ('Breathe', 'Telepopmusik', 'Genetic World'),
    ('Fade to Grey', 'Visage', 'Visage'),
    ('Blue (Da Ba Dee)', 'Eiffel 65', 'Europop'),
    ('Sandstorm', 'Darude', 'Before the Storm'),
    ('Kernkraft 400', 'Zombie Nation', 'Kernkraft 400'),
    ('Children', 'Robert Miles', 'Dreamland'),
    ('Driftwood', 'Robert Miles', 'Dreamland'),
    ('One and One', 'Robert Miles', 'Dreamland'),
    ('Fable', 'Robert Miles', 'Dreamland'),
    ('Sweet Harmony', 'The Beloved', 'Happiness'),
    ('Insomnia', 'Faithless', 'Reverence'),
    ('God Is a DJ', 'Faithless', 'Sunday 8pm'),
    ('We Come 1', 'Faithless', 'Outrospective'),
    ('Mass Destruction', 'Faithless', 'No Roots'),
    ('Orinoco Flow', 'Enya', 'Watermark'),
    ('Only Time', 'Enya', 'A Day Without Rain'),
    ('Mad World', 'Tears for Fears', 'The Hurting'),
    ('Shout', 'Tears for Fears', 'Songs from the Big Chair'),
    ('Everybody Wants to Rule the World', 'Tears for Fears', 'Songs from the Big Chair'),
    ('Head Over Heels', 'Tears for Fears', 'Songs from the Big Chair'),
    ('Pale Shelter', 'Tears for Fears', 'The Hurting'),
    ('Club Tropicana', 'Wham!', 'Fantastic'),
    ('Wake Me Up Before You Go-Go', 'Wham!', 'Make It Big'),
    ('Careless Whisper', 'George Michael', 'Make It Big'),
    ('Always on My Mind', 'Pet Shop Boys', 'Actually'),
    ('West End Girls', 'Pet Shop Boys', 'Please'),
]


def build_playlist(song_list: list) -> LinkedList:
    playlist = LinkedList()

    for song, artist, album in song_list:
        node = Node(song, artist, album)
        playlist.insert_at_end(node)

    return playlist